In [8]:
import datetime
import numpy as np
import pandas as pd
%matplotlib inline
import pandas_datareader.data as web
import fix_yahoo_finance as yf
import math

In [7]:
stocks = ['MS']
#          ,'GS','JPM','C']
start = datetime.datetime(2013,1,1)
end = datetime.datetime(2018,9,24)
df = yf.download(stocks,start = start,end = end)
df

[*********************100%***********************]  1 of 1 downloaded

                 Open       High        Low      Close  Adj Close    Volume
Date
2013-01-02  20.160000  20.170000  19.510000  19.620001  17.757097  29812900
2013-01-03  19.459999  19.610001  19.320000  19.580000  17.720900  29859500
2013-01-04  19.680000  20.250000  19.580000  20.190001  18.272972  31983900
2013-01-07  20.020000  20.129999  19.670000  19.799999  17.920004  21445100
2013-01-08  19.740000  19.790001  19.590000  19.650000  17.784254  22206200
2013-01-09  19.700001  19.940001  19.410000  19.620001  17.757097  26993800
2013-01-10  19.860001  20.430000  19.820000  20.340000  18.408737  39869800
2013-01-11  20.160000  20.420000  20.090000  20.170000  18.254877  20880000
2013-01-14  20.240000  20.240000  19.750000  20.070000  18.164373  14590200
2013-01-15  19.930000  20.540001  19.850000  20.430000  18.490187  25277000
2013-01-16  20.730000  20.860001  20.360001  20.540001  18.589746  30630600
2013-01-17  20.549999  20.750000  20.400000  20.750000  18.779806  26063600
2013-01-18  21.980000  22.459999  21.790001  22.379999  20.255039  65729400
2013-01-22  22.129999  22.980000  22.030001  22.980000  20.798069  38089200
2013-01-23  22.860001  22.940001  22.469999  22.670000  20.517506  24266100
2013-01-24  22.570000  23.030001  22.510000  22.600000  20.454151  20294700
2013-01-25  22.750000  22.850000  22.580000  22.700001  20.544659  14059600
2013-01-28  22.790001  22.790001  22.309999  22.309999  20.191687  13892000
2013-01-29  22.280001  22.670000  22.049999  22.590000  20.445103  14548300
2013-01-30  22.360001  23.000000  22.360001  22.980000  20.798069  23160400
2013-01-31  22.799999  23.020000  22.610001  22.850000  20.680414  19819100
2013-02-01  23.040001  23.740000  22.969999  23.510000  21.324409  31744400
2013-02-04  22.840000  23.139999  22.820000  22.879999  20.752975  26405700
2013-02-05  23.170000  23.490000  23.010000  23.400000  21.224634  23873200
2013-02-06  23.240000  23.500000  23.170000  23.389999  21.215563  15851000
2013-02-07  23.360001  23.580000  22.670000  23.100000  20.952530  20157900
2013-02-08  23.080000  23.410000  23.040001  23.320000  21.152073  16025800
2013-02-11  23.209999  23.469999  23.129999  23.280001  21.115791  10258200
2013-02-12  23.299999  23.650000  23.200001  23.629999  21.433254  15347000
2013-02-13  23.670000  23.870001  23.389999  23.629999  21.433254  15783400
...               ...        ...        ...        ...        ...       ...
2018-08-13  48.340000  48.480000  47.279999  47.349998  47.026791  11445900
2018-08-14  47.500000  48.040001  47.400002  47.860001  47.533314   8695500
2018-08-15  47.259998  47.590000  47.020000  47.450001  47.126110   9496100
2018-08-16  47.830002  48.590000  47.799999  48.299999  47.970306   8264500
2018-08-17  48.169998  48.610001  48.169998  48.369999  48.039829   5854500
2018-08-20  48.330002  48.590000  48.150002  48.290001  47.960377   7898200
2018-08-21  48.119999  48.939999  48.009998  48.540001  48.208672   9632000
2018-08-22  48.360001  48.660000  48.240002  48.599998  48.268257   4952000
2018-08-23  48.419998  48.720001  47.980000  48.130001  47.801468   7699300
2018-08-24  48.340000  48.610001  48.099998  48.139999  47.811398   5620600
2018-08-27  48.480000  50.099998  48.419998  49.889999  49.549454  13317400
2018-08-28  50.049999  50.430000  49.880001  50.000000  49.658703   7419100
2018-08-29  50.000000  50.189999  49.580002  49.950001  49.609047   7856700
2018-08-30  49.770000  49.889999  49.200001  49.299999  48.963482  11399900
2018-08-31  49.090000  49.090000  48.570000  48.830002  48.496693   7698400
2018-09-04  48.860001  48.910000  48.180000  48.709999  48.377510   8548700
2018-09-05  48.650002  49.049999  48.509998  48.720001  48.387444   5527500
2018-09-06  48.549999  48.820000  47.680000  47.930000  47.602833   7990500
2018-09-07  48.020000  48.400002  47.880001  48.220001  47.890854   7285200
2018-09-10  48.369999  48.470001  47.910000  47.939999  47.612762   4925000
2018-09-11  47.709999  48.040001  47.389999  47.860001  47.533314   5011700
2018-09-12  47.790001  48.099998  47.259998  47.480000  47.155903   6231800
2018-09-13  47.730000  48.099998  47.500000  47.720001  47.394268   8380100
2018-09-14  47.889999  48.509998  47.849998  48.189999  47.861057   6955500
2018-09-17  48.500000  48.540001  47.560001  47.680000  47.354542   6726500
2018-09-18  47.860001  48.040001  47.549999  47.849998  47.523376   7082500
2018-09-19  47.880001  49.360001  47.880001  49.099998  48.764847  12489100
2018-09-20  49.750000  50.369999  49.709999  49.880001  49.539524  11810000
2018-09-21  49.930000  49.970001  49.150002  49.410000  49.072731  21450400
2018-09-24  49.369999  49.450001  48.480000  48.560001  48.228535   7917600

[1443 rows x 6 columns]

In [11]:
def get_moving_average(df, window):
    df['Normal Return'] = df['Adj Close'].pct_change()
    df[str(window) + 'day MA'] = df['Adj Close'].rolling(window).mean()
    df['Signal'] = np.where(df[str(window) + 'day MA'] > df['Adj Close'],1,0)
    df['Log Return'] = df['Normal Return'].apply(lambda x:math.log(x+1))
    df['Strat Daily Return'] = np.where(df['Signal'] == 1, -df['Log Return'],0)
    df['Cumulative Sum'] = df['Strat Daily Return'].cumsum()
    return df

In [12]:
get_moving_average(df,180)

,Open,High,Low,Close,Adj Close,Volume,Normal Return,180day MA,Signal,Log Return,Strat Daily Return,Cumulative Sum
Date,,,,,,,,,,,,
2013-01-02,20.160000,20.170000,19.510000,19.620001,17.757097,29812900,NaN,NaN,0,NaN,0.000000,0.000000
2013-01-03,19.459999,19.610001,19.320000,19.580000,17.720900,29859500,-0.002038,NaN,0,-0.002041,0.000000,0.000000
2013-01-04,19.680000,20.250000,19.580000,20.190001,18.272972,31983900,0.031154,NaN,0,0.030678,0.000000,0.000000
2013-01-07,20.020000,20.129999,19.670000,19.799999,17.920004,21445100,-0.019316,NaN,0,-0.019505,0.000000,0.000000
2013-01-08,19.740000,19.790001,19.590000,19.650000,17.784254,22206200,-0.007575,NaN,0,-0.007604,0.000000,0.000000
2013-01-09,19.700001,19.940001,19.410000,19.620001,17.757097,26993800,-0.001527,NaN,0,-0.001528,0.000000,0.000000
2013-01-10,19.860001,20.430000,19.820000,20.340000,18.408737,39869800,0.036697,NaN,0,0.036040,0.000000,0.000000
2013-01-11,20.160000,20.420000,20.090000,20.170000,18.254877,20880000,-0.008358,NaN,0,-0.008393,0.000000,0.000000
2013-01-14,20.240000,20.240000,19.750000,20.070000,18.164373,14590200,-0.004958,NaN,0,-0.004970,0.000000,0.000000
2013-01-15,19.930000,20.540001,19.850000,20.430000,18.490187,25277000,0.017937,NaN,0,0.017778,0.000000,0.000000
2013-01-16,20.730000,20.860001,20.360001,20.540001,18.589746,30630600,0.005384,NaN,0,0.005370,0.000000,0.000000
2013-01-17,20.549999,20.750000,20.400000,20.750000,18.779806,26063600,0.010224,NaN,0,0.010172,0.000000,0.000000
2013-01-18,21.980000,22.459999,21.790001,22.379999,20.255039,65729400,0.078554,NaN,0,0.075621,0.000000,0.000000
2013-01-22,22.129999,22.980000,22.030001,22.980000,20.798069,38089200,0.026810,NaN,0,0.026457,0.000000,0.000000
2013-01-23,22.860001,22.940001,22.469999,22.670000,20.517506,24266100,-0.013490,NaN,0,-0.013582,0.000000,0.000000
2013-01-24,22.570000,23.030001,22.510000,22.600000,20.454151,20294700,-0.003088,NaN,0,-0.003093,0.000000,0.000000
2013-01-25,22.750000,22.850000,22.580000,22.700001,20.544659,14059600,0.004425,NaN,0,0.004415,0.000000,0.000000
2013-01-28,22.790001,22.790001,22.309999,22.309999,20.191687,13892000,-0.017181,NaN,0,-0.017330,0.000000,0.000000
2013-01-29,22.280001,22.670000,22.049999,22.590000,20.445103,14548300,0.012551,NaN,0,0.012472,0.000000,0.000000
2013-01-30,22.360001,23.000000,22.360001,22.980000,20.798069,23160400,0.017264,NaN,0,0.017117,0.000000,0.000000
2013-01-31,22.799999,23.020000,22.610001,22.850000,20.680414,19819100,-0.005657,NaN,0,-0.005673,0.000000,0.000000
2013-02-01,23.040001,23.740000,22.969999,23.510000,21.324409,31744400,0.031140,NaN,0,0.030665,0.000000,0.000000
2013-02-04,22.840000,23.139999,22.820000,22.879999,20.752975,26405700,-0.026797,NaN,0,-0.027163,0.000000,0.000000
2013-02-05,23.170000,23.490000,23.010000,23.400000,21.224634,23873200,0.022727,NaN,0,0.022473,0.000000,0.000000
2013-02-06,23.240000,23.500000,23.170000,23.389999,21.215563,15851000,-0.000427,NaN,0,-0.000427,0.000000,0.000000
2013-02-07,23.360001,23.580000,22.670000,23.100000,20.952530,20157900,-0.012398,NaN,0,-0.012476,0.000000,0.000000
2013-02-08,23.080000,23.410000,23.040001,23.320000,21.152073,16025800,0.009524,NaN,0,0.009479,0.000000,0.000000
2013-02-11,23.209999,23.469999,23.129999,23.280001,21.115791,10258200,-0.001715,NaN,0,-0.001717,0.000000,0.000000
2013-02-12,23.299999,23.650000,23.200001,23.629999,21.433254,15347000,0.015034,NaN,0,0.014922,0.000000,0.000000
2013-02-13,23.670000,23.870001,23.389999,23.629999,21.433254,15783400,0.000000,NaN,0,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
2018-08-13,48.340000,48.480000,47.279999,47.349998,47.026791,11445900,-0.021492,51.948424,1,-0.021726,0.021726,0.555966
2018-08-14,47.500000,48.040001,47.400002,47.860001,47.533314,8695500,0.010771,51.945848,1,0.010713,-0.010713,0.545253
2018-08-15,47.259998,47.590000,47.020000,47.450001,47.126110,9496100,-0.008567,51.941336,1,-0.008604,0.008604,0.553856
2018-08-16,47.830002,48.590000,47.799999,48.299999,47.970306,8264500,0.017914,51.933904,1,0.017755,-0.017755,0.536101
2018-08-17,48.169998,48.610001,48.169998,48.369999,48.039829,5854500,0.001449,51.921859,1,0.001448,-0.001448,0.534653
2018-08-20,48.330002,48.590000,48.150002,48.290001,47.960377,7898200,-0.001654,51.907795,1,-0.001655,0.001655,0.536308
2018-08-21,48.119999,48.939999,48.009998,48.540001,48.208672,9632000,0.005177,51.893264,1,0.005164,-0.005164,0.531145
2018-08-22,48.360001,48.660000,48.240002,48.599998,48.268257,4952000,0.001236,51.875095,1,0.001235,-0.001235,0.529909
2018-08-23,48.419998,48.720001,47.980000,48.130001,47.801468,7699300,-0.009671,51.857975,1,-0.009718,0.009718,0.539627
2018-08-24,48.340000,48.610001,48.099998,48.139999,47.811398,5620600,0.000208,51.842649,1,0.000208,-0.000208,0.539419
2018-08-27,48.480000,50.099998,48.419998,49.889999,49.549454,13317400,0.036352,51.833392,1,0.035707,-0.035707,0.503712
2018-08-28,50.049999,50.430000,49.880001,50.000000,49.658703,7419100,0.002205,51.821807,1,0.002202,-0.002202,0.501510
2018-08-29,50.000000,50.189999,49.580002,49.950001,49.609047,7856700,-0.001000,51.810598,1,-0.001000,0.001000,0.502510
2018-08-30,49.770000,49.889999,49.200001,49.299999,48.963482,11399900,-0.013013,51.789933,1,-0.013098,0.013098,0.515609
2018-08-31,49.090000,49.090000,48.570000,48.830002,48.496693,7698400,-0.009533,51.770316,1,-0.009579,0.009579,0.525188
2018-09-04,48.860001,48.910000,48.180000,48.709999,48.377510,8548700,-0.002458,51.752972,1,-0.002461,0.002461,0.527649
2018-09-05,48.650002,49.049999,48.509998,48.720001,48.387444,5527500,0.000205,51.733183,1,0.000205,-0.000205,0.527443
2018-09-06,48.549999,48.820000,47.680000,47.930000,47.602833,7990500,-0.016215,51.708274,1,-0.016348,0.016348,0.543791
2018-09-07,48.020000,48.400002,47.880001,48.220001,47.890854,7285200,0.006051,51.686650,1,0.006032,-0.006032,0.537759
2018-09-10,48.369999,48.470001,47.910000,47.939999,47.612762,4925000,-0.005807,51.665764,1,-0.005824,0.005824,0.543583
2018-09-11,47.709999,48.040001,47.389999,47.860001,47.533314,5011700,-0.001669,51.642425,1,-0.001670,0.001670,0.545253
2018-09-12,47.790001,48.099998,47.259998,47.480000,47.155903,6231800,-0.007940,51.617859,1,-0.007972,0.007972,0.553224
2018-09-13,47.730000,48.099998,47.500000,47.720001,47.394268,8380100,0.005055,51.595977,1,0.005042,-0.005042,0.548182
2018-09-14,47.889999,48.509998,47.849998,48.189999,47.861057,6955500,0.009849,51.576144,1,0.009801,-0.009801,0.538381
2018-09-17,48.500000,48.540001,47.560001,47.680000,47.354542,6726500,-0.010583,51.553062,1,-0.010639,0.010639,0.549021
2018-09-18,47.860001,48.040001,47.549999,47.849998,47.523376,7082500,0.003565,51.531897,1,0.003559,-0.003559,0.545462
2018-09-19,47.880001,49.360001,47.880001,49.099998,48.764847,12489100,0.026123,51.519151,1,0.025788,-0.025788,0.519674
2018-09-20,49.750000,50.369999,49.709999,49.880001,49.539524,11810000,0.015886,51.509947,1,0.015761,-0.015761,0.503913
2018-09-21,49.930000,49.970001,49.150002,49.410000,49.072731,21450400,-0.009423,51.493802,1,-0.009467,0.009467,0.513380
2018-09-24,49.369999,49.450001,48.480000,48.560001,48.228535,7917600,-0.017203,51.473076,1,-0.017353,0.017353,0.530733

In [11]:
import requests
from bs4 import BeautifulSoup
url = "https://www.briefing.com/investor/markets/stock-market-update/"
response = requests.get(url)
#response.status_code
results_page = BeautifulSoup(response.content,'lxml')
#print(results_page.prettify())
tag = results_page.find('td', valign="top").get_text()
#all_td_tags = results_page.find_all('td', valign="top")
#index_name = tag.find('td', valign="top").get_text()
#class_ = 'valign'
#all_td_tags
#index_name
tag

'Dow'

In [16]:
url = "https://www.briefing.com/investor/markets/stock-market-update/"
response = requests.get(url)
results_page = BeautifulSoup(response.content,'lxml')
all_td_tags = results_page.find_all('td', valign="top")
for tag in all_td_tags:
    index_list = []
    count = 1
    while count < 4:
        if count % 4 == 1:
            print(tag.get_text())
            index_name = tag.find('td').get_text()
            index_list.append(index_name)
        elif count % 4 == 2:
            index_data = tag.find('td').get_text()
            index_list.append(index_data)
        elif count % 4 == 3:
            index_change = tag.find('td').get_text()
            index_list.append(index_change)
        elif count % 4 == 0:
            index_change_pct = tag.find('td').get_text()
            index_list.append(index_change_pct)
        count+=1
    index_dict[index_name] = index_list

Dow

AttributeError: 'NoneType' object has no attribute 'get_text'

In [72]:
def get_current_index():
    import requests
    import pandas as pd
    from bs4 import BeautifulSoup
    index_dict = dict()
    url = "https://www.briefing.com/investor/markets/stock-market-update/"
    response = requests.get(url)
    results_page = BeautifulSoup(response.content,'lxml')
    all_td_tags = results_page.find_all('td', valign="top")
    count = 1
    index_list = []
    for tag in all_td_tags:
        if count % 4 == 1:
            index_name = tag.get_text()
        elif count % 4 == 2:
            index_data = tag.get_text()
        elif count % 4 == 3:
            index_change = tag.get_text()
        elif count % 4 == 0:
            index_change_pct = tag.get_text().strip()
            index_change_pct = index_change_pct.replace('(','')
            index_change_pct = index_change_pct.replace(')','')
            index_change_pct = index_change_pct.replace('%','')
            index_tuple = (index_name,index_data,index_change,index_change_pct)
            index_list.append(index_tuple)
        if count == 12:
            break
        count+=1
    
    index_name_list = [index_list[i][0] for i in range(3)]
    index_data_list = [index_list[i][1] for i in range(3)]
    index_change_list = [index_list[i][2] for i in range(3)]
    index_change_pct_list = [index_list[i][3] for i in range(3)]
    df = pd.DataFrame([index_name_list,index_data_list,index_change_list,index_change_pct_list])
    return df

In [73]:
get_current_index()

          0        1        2
0       Dow   Nasdaq   SP 500
1  24284.85  6939.19  2632.70
2   -178.84   -33.27   -17.37
3     -0.73    -0.48    -0.66

In [76]:
def get_current_industry_watch():
    import requests
    import pandas as pd
    from bs4 import BeautifulSoup
    index_dict = dict()
    url = "https://www.briefing.com/investor/markets/stock-market-update/"
    response = requests.get(url)
    results_page = BeautifulSoup(response.content,'lxml')
    all_td_tags = results_page.find_all('td', valign="top")
    count = 1
    strong_list = []
    weak_list = []
    for tag in all_td_tags:
        if count == 17:
            print(tag.get_text())
        if count == 18:
            print(tag.get_text())
        count += 1

In [77]:
get_current_industry_watch()

Strong: Consumer Staples, Health Care, Industrials, Utilities
Weak: Energy, Materials, Communication Services

In [81]:
def get_moving_the_market():
    import requests
    import pandas as pd
    from bs4 import BeautifulSoup
    index_dict = dict()
    url = "https://www.briefing.com/investor/markets/stock-market-update/"
    response = requests.get(url)
    results_page = BeautifulSoup(response.content,'lxml')
    all_td_tags = results_page.find_all('td')
    count = 1
    for tag in all_td_tags:
        if count == 32:
            print("Moving the Market:")
            print(tag.get_text())
        count+=1

In [82]:
get_moving_the_market()

Moving the Market:
Energy stocks weigh as WTI crude slips to a 13-month lowFANG stocks continue to struggle; Facebook (FB), Apple (AAPL) lead retreatThe stock market will close at 1:00 PM ET, and the bond market will close at 2:00 PM ET; reduced post-holiday participation could lead to volatile session